### ISSUE TITLE
Finding supplemental data

### ISSUE THREAD

**Issue by devMattO** [devMattO/New-Coders-Survey-Data-Visualizations#11]
median salary -- as jr. dev (most common position of bootcamp graduates)
unemployment rate
number of jobs
growth in the industry

**Comment by devMattO** [comment]
http://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm#tab-1

**Comment by drewpchannel** [comment]
job sites have APIs, might be useful

**Comment by panicboy** [comment]
Discuss whether to use BLS API or import their data @ next scrum
